Repository astropy/regions, pull requests merged in 2018-08, with the labels that each got.

#207 Remove Python 3.4 build from travis-ci
  .travis.yml
Labels: infrastructure

#209 Remove shapely converter functions, keep docs page
  docs/installation.rst
  docs/shapely.rst
  regions/core/compound.py
  regions/core/core.py
  regions/core/pixcoord.py
  regions/core/tests/test_pixcoord.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/line.py
  regions/shapes/point.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/tests/test_api.py
  regions/shapes/tests/test_common.py
  regions/shapes/tests/utils.py
Labels: API, question

#208 Add support for python 3.7 in travis ci
  .travis.yml
  appveyor.yml
Labels: enhancement, infrastructure

#212 Add astropy-healpix as a dep
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  regions/conftest.py
  setup.py
Labels: infrastructure

#214 added CHANGES.rst
  CHANGES.rst
  docs/changelog.rst
  docs/conf.py
  docs/index.rst
Labels: docs

#213 Rectangles -> Polygons
  regions/shapes/rectangle.py
  regions/shapes/tests/test_rectangle.py
Labels: enhancement

#218 Refactor as_patch->as_artist
  CHANGES.rst
  docs/masks.rst
  docs/plotting.rst
  regions/core/bounding_box.py
  regions/core/compound.py
  regions/core/core.py
  regions/core/tests/test_bounding_box.py
  regions/shapes/annulus.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/line.py
  regions/shapes/point.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/tests/test_circle.py
  regions/shapes/tests/test_ellipse.py
  regions/shapes/tests/test_line.py
  regions/shapes/tests/test_point.py
  regions/shapes/tests/test_polygon.py
  regions/shapes/tests/test_rectangle.py
  regions/shapes/text.py
Labels: API, enhancement
