Repository astropy/regions, pull requests merged in 2019-06, with the labels that each got.

#264 Minor maintanance
  .travis.yml
  regions/io/fits/tests/test_fits_region.py
  setup.cfg
Labels: infrastructure

#263 Enable doctests
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  docs/compound.rst
  docs/contains.rst
  docs/crtf.rst
  docs/ds9.rst
  docs/fits_region.rst
  docs/getting_started.rst
  docs/index.rst
  docs/masks.rst
  docs/plot_compound.py
  docs/plot_example.py
  docs/plot_example_pix.py
  docs/plot_reg.py
  docs/plotting.rst
  docs/shapely.rst
  docs/shapes.rst
  regions/_utils/examples.py
  regions/core/bounding_box.py
  regions/io/crtf/read.py
  regions/io/crtf/write.py
  regions/io/ds9/read.py
  regions/io/ds9/tests/data/plot_image.reg
  regions/io/fits/read.py
  regions/shapes/annulus.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/line.py
  regions/shapes/point.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/text.py
  setup.cfg
Labels: docs, infrastructure

#277 Add BoundingBox union and intersection
  CHANGES.rst
  regions/core/bounding_box.py
  regions/core/tests/test_bounding_box.py
Labels: enhancement

#278 Fix corner-case issue in RegionMask.multiply()
  CHANGES.rst
  regions/core/mask.py
  regions/core/tests/test_mask.py
Labels: bug

#269 Add region copy methods
  regions/core/pixcoord.py
  regions/core/tests/test_pixcoord.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/tests/test_circle.py
  regions/shapes/tests/test_ellipse.py
  regions/shapes/tests/test_polygon.py
  regions/shapes/tests/test_rectangle.py
Labels: enhancement

#282 Add python_requires to setup.py
  setup.py
Labels: infrastructure

#281 Change copy and add rotate methods
  regions/core/core.py
  regions/core/pixcoord.py
  regions/core/tests/test_pixcoord.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/tests/test_circle.py
  regions/shapes/tests/test_ellipse.py
  regions/shapes/tests/test_polygon.py
  regions/shapes/tests/test_rectangle.py
Labels: enhancement

#279 Simplify annulus regions?
  regions/core/attributes.py
  regions/shapes/annulus.py
  regions/shapes/tests/test_api.py
Labels: question

#283 Add region copy test for all regions
  regions/shapes/point.py
  regions/shapes/tests/test_annulus.py
  regions/shapes/tests/test_api.py
  regions/shapes/tests/test_line.py
  regions/shapes/tests/test_point.py
  regions/shapes/tests/test_text.py
Labels: testing

#284 Simplify property validation and add compound copy
  regions/core/attributes.py
  regions/core/tests/test_compound.py
Labels: enhancement

#285 Implement rotate method for more regions
  regions/core/compound.py
  regions/core/tests/test_compound.py
  regions/shapes/annulus.py
  regions/shapes/line.py
  regions/shapes/point.py
  regions/shapes/tests/test_annulus.py
  regions/shapes/tests/test_line.py
  regions/shapes/tests/test_point.py
  regions/shapes/tests/test_text.py
Labels: enhancement

#286 Change _repr_params to _fields, including center
  docs/crtf.rst
  docs/ds9.rst
  regions/core/compound.py
  regions/core/core.py
  regions/io/fits/read.py
  regions/shapes/annulus.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/line.py
  regions/shapes/point.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/tests/test_annulus.py
  regions/shapes/tests/test_circle.py
  regions/shapes/tests/test_ellipse.py
  regions/shapes/tests/test_point.py
  regions/shapes/tests/test_rectangle.py
  regions/shapes/tests/test_text.py
  regions/shapes/text.py
Labels: enhancement
