Repository astropy/regions, pull requests merged in 2022-10, with the labels that each got.

#479 Update required Cython version
  pyproject.toml
Labels: infrastructure, no-changelog-entry-needed

#481 Use SPDX license expression in project metadata
  setup.cfg
Labels: infrastructure, no-changelog-entry-needed

#482 Use unified WCS methods
  regions/shapes/annulus.py
  regions/shapes/circle.py
  regions/shapes/ellipse.py
  regions/shapes/line.py
  regions/shapes/point.py
  regions/shapes/polygon.py
  regions/shapes/rectangle.py
  regions/shapes/text.py
Labels: no-changelog-entry-needed, shapes

#408 Fix for Issue 407: CRTF region parsing
  regions/io/crtf/read.py
  regions/io/crtf/tests/data/crtf_carta_sexagesimal.crtf
  regions/io/crtf/tests/test_crtf.py
Labels: bug, io.crtf

#483 Update testing and actions configurations
  .github/workflows/ci_tests.yml
  .github/workflows/cron_tests.yml
  .gitignore
  CITATION.md
  LICENSE.rst
  RELEASING.rst
  pyproject.toml
  regions/CITATION.rst
  tox.ini
Labels: testing, infrastructure, no-changelog-entry-needed

#484 Add publish workflow to Actions
  .github/workflows/publish.yml
Labels: infrastructure, no-changelog-entry-needed, Build all wheels

#485 Update installation docs
  docs/install.rst
Labels: docs, no-changelog-entry-needed
