Repository astropy/regions, pull requests merged in 2023-12, with the labels that each got.

#539 BLD: pin extension-helpers to 1.* following upstream recommendation
  pyproject.toml
Labels: infrastructure, no-changelog-entry-needed

#540 Fix devdeps
  pyproject.toml
  tox.ini
Labels: testing, no-changelog-entry-needed

#541 Remove setup.py
  setup.py
Labels: infrastructure, no-changelog-entry-needed

#542 Bump actions/setup-python from 4 to 5
  .github/workflows/ci_cron_daily.yml
  .github/workflows/ci_cron_weekly.yml
  .github/workflows/ci_tests.yml
Labels: testing, infrastructure
