Repository astropy/regions, pull requests merged in 2025-06, with the labels that each got.

#598 Enable limited API builds and bump minimum Python to 3.11
  .github/workflows/ci_tests.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  docs/conf.py
  pyproject.toml
  tox.ini
Labels: infrastructure, Build all wheels, Arch CI

#601 Update installation docs
  .flake8
  .pycodestyle
  CHANGES.rst
  LICENSE.rst
  docs/install.rst
  pyproject.toml
Labels: docs, installation

#602 Partial revert of limited API builds
  .github/workflows/ci_tests.yml
  pyproject.toml
Labels: no-changelog-entry-needed, installation

#603 Package infrastructure updates
  .pre-commit-config.yaml
  .readthedocs.yaml
  tox.ini
Labels: testing, infrastructure, no-changelog-entry-needed

#604 Re-enable Limited API
  pyproject.toml
Labels: Build all wheels
